# Generated by Django 4.2.13 on 2024-06-23 05:32

from django.db import migrations, models
import pandas as pd

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    def insert_init_data(apps, schema_editor):
    # Cargar data del csv.
        data = pd.read_csv(r'C:\Users\MARTIN\Desktop\PROYECTOS\HACKATON\4_ALERTA_RIMAC_BACKEND\apps\eventos\migrations\data_eventos.csv')
        Evento = apps.get_model('eventos', 'Eventos')

        lista_eventos = []
        
        for i, row in data.iterrows():            
            lista_eventos.append(Evento(latitud= row['lat'], longitud=row['lng'], estado=row['status'], fecha=row['date'], tipo=row['type'], color=row['color']))
        Evento.objects.bulk_create(lista_eventos)
    
    def undo_insert_data(apps, schema_editor):
        Evento = apps.get_model('eventos', 'Eventos')
        Evento.objects.all().delete()
        
    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created= True, primary_key= True, serialize= False, verbose_name= 'ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('estado', models.TextField(max_length= 50)),
                ('fecha', models.DateTimeField(auto_now_add= True, null= True)),
                ('tipo', models.TextField(max_length= 300)),
                ('color', models.TextField(max_length= 20)),
            ],
        ),
        migrations.RunPython(insert_init_data, reverse_code= undo_insert_data)
    ]
