# Generated by Django 4.2.13 on 2024-06-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='gemini_output',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
